spring:
  datasource:
    username: yejidaxuesheng
    password: Root123456
    url: jdbc:mysql://rm-m5e9591dp3p323kgp3o.mysql.rds.aliyuncs.com:3306/springdemo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5Dialect

mybatis:
  mapper-locations: classpath:com/example/demo/modules/**/mapper/xml/*.xml
  type-aliases-package: com.example.demo.modules
debug: true
logging:
  level:
    com.example.demo.modules:
      DEBUG

